### ISSUE TITLE
Difference between ecmwf_grib and python-ecmwf_grib 

### ISSUE THREAD

**Issue by knedlsepp** [conda-forge/python-ecmwf_grib-feedstock#19]
I was wondering how is this different from: https://github.com/conda-forge/ecmwf_grib-feedstock ?

**Comment by ocefpaf** [comment]
This is the python wrapper of the `ecmwf_grib` lib.

Just recently `conda` added the functionality to create two packages from a single recipe.
We should, in the future, try to use that and unify these two into one feedstock.
However, keeping them as separate packages is highly desirable because the `python` wrapper needs to be built for every python version and depend on Python, while the lib is built only once and has no dependency on Python.

**Comment by knedlsepp** [comment]
Thanks for clarifying!
